package menea.Client.Console;

/**
 *
 * @author melissa
 */
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import menea.Models.CommandInterpreter;
import menea.Tiles.Board;

public class FrameConsole extends javax.swing.JFrame {
    
    private CommandInterpreter interpreter;
    private Board boardRef;
    private GraphicsDevice gd;
    
    private static final String IMAGE_PATH = "/assets/";
    private Image ImageFondo;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameConsole.class.getName());

    /**
     * Creates new form FrameConsole
     */
    
    public FrameConsole() {
        initComponents();
    
        txfCommandConsult.addActionListener(e -> ProcesarComando());
        gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        try {
            gd.setFullScreenWindow(this);
        } catch (Exception e) {
            System.out.println("Error cargando pantalla" + e.getMessage());
        }
    
    }
    
    public void loadImage() {
        try {

            imageFondo = ImageIO.read(getClass().getResource(IMAGE_PATH + "BlackManta.png"));

            background = background.getScaledInstance(260, 200, Image.SCALE_SMOOTH);

           ImageIO.read(getClass().getResource(IMAGE_PATH + "AndrewGarfield.png"))
                    .getScaledInstance(260, 200, Image.SCALE_SMOOTH));
    
        } catch (IOException e) {
            System.out.println("No se pudo cargar");
        }
    }
    
    public void attachBoard(Board board) {
        this.boardRef = board;
        plnMatriz.repaint();       
    }

    public void refreshBoard() {
        plnMatriz.repaint();
    }
    
    public void attachInterpreter(CommandInterpreter interpreter) {
        this.interpreter = interpreter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        txfCommandConsult = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaLog = new javax.swing.JTextArea();
        txfCommand1 = new javax.swing.JTextField();
        pnlFondo = new javax.swing.JPanel();
        plnMatriz = new javax.swing.JPanel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txaLog.setEditable(false);
        txaLog.setColumns(20);
        txaLog.setLineWrap(true);
        txaLog.setRows(5);
        jScrollPane2.setViewportView(txaLog);

        pnlFondo.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        plnMatriz.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout plnMatrizLayout = new javax.swing.GroupLayout(plnMatriz);
        plnMatriz.setLayout(plnMatrizLayout);
        plnMatrizLayout.setHorizontalGroup(
            plnMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );
        plnMatrizLayout.setVerticalGroup(
            plnMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(plnMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 753, Short.MAX_VALUE))
                    .addComponent(txfCommandConsult)
                    .addComponent(txfCommand1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plnMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)))
                .addComponent(txfCommandConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfCommand1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        
    public void log(String message) {
        txaLog.append(message + "\n"); //agregar una línea a la bitácora 
    }
    
    private void ProcesarComando() {
        String comando = txfCommandConsult.getText().trim(); //trim para eliminar espacios en blancos d l q el usuario ingrese 
        if (comando.isEmpty()) return; //

        log(">" + comando); // > para que se note q es entrada del jugador
        txfCommandConsult.setText("");

        if (interpreter != null) {
            interpreter.handle(comando); 
        } else {
            log("Error, Intérprete no inicializado.");
            }
        }
        public void logAttack(int dmg, int attacker, int target) {
        log("Jugador " + attacker + " atacó al jugador " + target + " con daño de " + dmg);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameConsole().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel plnMatriz;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTextArea txaLog;
    private javax.swing.JTextField txfCommand1;
    private javax.swing.JTextField txfCommandConsult;
    // End of variables declaration//GEN-END:variables
}
